FlowerScrets/FlowerScrets/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from core.views import *

urlpatterns = [
    path('',include('core.urls')),
    path('crud/',include('crud.urls')),
    path('admin/', admin.site.urls),
    path('api/',include('api.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
 

FlowerScrets/api/urls.py
from django.urls import path
from .views import *

urlpatterns =[
    path('productos/',productos_list),
    path('categorias/',categoria_list),
    path('cuentas/',cuenta_list),
    path('productos/<str:product_id>',productos_detail),
]

FlowerScrets/core/urls.py
from django.urls import path

from crud.views import product_by_categoria
from .views import *


urlpatterns = [
    path('',root),
    path('home', home,name="home"),

    path('maceteros',maceteros,name="maceteros"),
    path('maceteros/<int:categoria>',product_by_categoria,name="productos-categoria"),

    path('flores',flores,name="flores"),
    path('flores/<int:categoria>',product_by_categoria,name="productos-categoria"),

    path('tierra',tierra,name="tierra"),
    path('subscripcion',subscripcion,name="subscripcion"),
    path('arbustos',arbustos,name="arbustos"),
    path('registro',registro,name="registro"),
    path('pago',pago,name="pago"),

    path('logeo',logeo,name="logeo"),
    path('logout',logout,name="logout"),

    path('agregar/<str:idProducto>/', agregar_producto, name="Add"),
    path('eliminar/<str:idProducto>/', eliminar_producto, name="Del"),
    path('restar/<str:idProducto>/', restar_producto, name="Sub"),
    path('limpiar/', limpiar_carrito, name="CLS"),
]

FlowerScrets/core/models.py
from django.db import models
from django.contrib.auth.models import User ## pasar
from django.contrib.auth.models import AbstractBaseUser
from django.db.models.signals import post_save # pasar
from django.dispatch import receiver #pasar


class Cuenta(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rut =  models.TextField(max_length=12)
    fechnac = models.DateField()
    numte = models.IntegerField()
    direcc = models.TextField()
    def str(self):
        return self.rut

FlowerScrets/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from crud.models import *
#SE AGREGO
from django.shortcuts import render, redirect
from django.http import HttpResponse
from crud.models import *
from django.contrib.auth import authenticate,login,logout as django_logout
from django.contrib import messages
#SE AGREGO
from django.contrib.auth.models import User
from core.models import Cuenta
from core.Carrito import *



#CREAR UN CONSTRUCTOR

class persona:
    def __init__(self, nombre,edad) -> None:
        self.nombre = nombre
        self.edad = edad


# Create your views here.

def root(request):
    return redirect('/home')

def home(request):

    #parecido a un json - recibe un objeto, lista, string, numero
    #actor = persona("Brad Pitt","58")
    #lista = ["Aladin","Los Increibles","Frozen"]
    #datos = {"nombre":"Mundo", "peliculas":lista ,"actor":actor}
    return render (request,'core/home.html')#,datos)

def maceteros(request):
    context = {'maceteros':Producto.objects.all()}
    return render(request,'core/maceteros.html',context)

def maceteros_by_categoria(request,categoria):
    maceteros = Producto.objects.filter(categoria=categoria)
    return render(request,'core/flores.html',{'maceteros':maceteros})
    
def flores(request):
    context = {'flores':Producto.objects.all()}
    return render(request,'core/flores.html',context)

def flores_by_categoria(request,categoria):
    flores = Producto.objects.filter(categoria=categoria)
    return render(request,'core/flores.html',{'flores':flores})

def subscripcion(request):
    return render(request,'core/subscripcion.html')

def tierra(request):
    return render(request,'core/tierra.html')

def arbustos(request):
    return render(request,'core/arbustos.html')

def registro(request):
    return render(request,'core/Registro.html')

def pago(request):
    return render(request,'core/pago.html')

def registro(request):
    if request.method=='POST':
        newusu = User.objects.create_user(username=request.POST['email'],email=request.POST['email'],password=request.POST['password'],first_name=request.POST['nombre'],last_name=request.POST['apellido'])
        ##usuario = User.objects.create_user(username='pepe',email='corneta@duoc.cl',password='elmaricon123')
        cuenta = Cuenta.objects.create(rut=request.POST['rut'],fechnac=request.POST['fechnac'],direcc=request.POST['direcc'],user_id=newusu.id,numte=request.POST['numte'])
       ##cuenta = Cuenta.objects.create(rut='20146051-4',fechnac='2022-06-22',direcc='av siempre viva',user_id=usuario.id,numte=74341877))
    return render(request,'core/Registro.html')


def logeo(request):
    if request.method=='POST':
        user= authenticate(username=request.POST['correo_login'],password=request.POST['password_login'])
        if user is not None:
            login(request,user)
            return redirect('home')
        else:
            messages.success(request, "USUARIO NO REGISTRADO O DATOS INCORRECTOS :V")
            return redirect('logeo')
    return render(request,'core/logeo.html')

def logout(request):
    if request.user.is_authenticated:
        django_logout(request)
    return redirect('home')

#carritoo
def agregar_producto(request, idProducto):
    carrito = Carrito(request)
    producto = Producto.objects.get(idProducto=idProducto)
    carrito.agregar(producto)
    return redirect('maceteros')

def eliminar_producto(request, idProducto):
    carrito = Carrito(request)
    producto = Producto.objects.get(idProducto=idProducto)
    carrito.eliminar(producto)
    return redirect('maceteros')

def restar_producto(request, idProducto):
    carrito = Carrito(request)
    producto = Producto.objects.get(idProducto=idProducto)
    carrito.restar(producto)
    return redirect('maceteros')

def limpiar_carrito(request):
    carrito = Carrito(request)
    carrito.limpiar()
    return redirect('maceteros')

FlowerScrets/core/templates/core/Logeo.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
<section class="formulario">
    <div class="row">

        <div class="col-lg-5 p-3" style="background: rgb(253, 254, 254,.3);">
            <img src="{% static 'core/images/img_reg.png' %}" alt="" style="height: 300px;" height="300px">
        </div>
        
        <div class="col-lg-7 p-5" style="background: rgb(253, 254, 254,.3);">
            <div class="signup-form">
                <form method="post" class="mt-5 border p-5 bg-light shadow" id="formulariologeo">
                    {% csrf_token %}
                    <h3>INICIO DE SESION</h3>
                    <div class="row">
                        <div class="alert alert-danger" role="alert" id="alerta">
                        </div>
                        
                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="text" class="form-control" id="id_email"  name="correo_login" placeholder="Nombre" style="font-size: 1.3rem;"/>
                            <label for="floatingInput">correo</label>
                        </div>
                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="password" class="form-control"  id="id_pass" placeholder="contraseña" style="font-size: 1.3rem;"  name="password_login"/>
                            <label for="floatingInput">contraseña</label>
                        </div>
                        <div class="d-flex justify-content-between">
                            <button type="submit" class="btn btn-outline-success" href="#" role="button" style="background-color: #67cb57; border-radius: 5rem; padding:.9rem 3.5rem;">Logear</button>
                        </div>

                    </div>
                </form>   
            </div> 
        </div>
    </div> 
</section>
{% endblock %}
{% block js %}
<script src="{% static 'core/jquery.rut.min.js' %}"></script>
{% endblock %}

FlowerScrets/core/templates/core/Registro.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
<section class="formulario">
    <div class="row">

        <div class="col-lg-5 p-3" style="background: rgb(253, 254, 254,.3);">
            <img src="{% static 'core/images/img_reg.png' %}" alt="" style="height: 300px;" height="300px">
        </div>
        
        <div class="col-lg-7 p-5" style="background: rgb(253, 254, 254,.3);">
            <div class="signup-form">
                <form method="post" class="mt-5 border p-5 bg-light shadow" id="formularioregistro">
                    {% csrf_token %}
                    <h3>REGISTRO</h3>
                    <div class="row">
                        <div class="alert alert-danger" role="alert" id="alerta">
                        </div>
                        
                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="text" class="form-control" id="id_nomb"  name="nombre" placeholder="Nombre" style="font-size: 1.3rem;">
                            <label for="floatingInput">Nombre</label>
                        </div>
                    
                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="text" class="form-control" id="id_ape" placeholder="Apellido" style="font-size: 1.3rem;"  name="apellido">
                            <label for="floatingPassword">Apellido</label>
                        </div>
                        
                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="text" class="form-control"  id="id_direc" placeholder="Dirección" style="font-size: 1.3rem;"  name="direcc">
                            <label for="floatingInput">Dirección</label>
                        </div>

                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="number" class="form-control" id="id_num" placeholder="Numero Telefonico" style="font-size: 1.3rem;"  name="numte">
                            <label for="floatingInput">Número Telefonico</label>
                        </div>

                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="email" class="form-control" id="id_email" placeholder="Email" style="font-size: 1.3rem;"  name="email">
                            <label for="floatingInput">Email</label>
                        </div>

                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="password" class="form-control" id="id_pass" placeholder="contraseña" style="font-size: 1.3rem;"  name="password">
                            <label for="floatingPassword">Contraseña</label>
                        </div>

                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="date" class="form-control" id="id_date" placeholder="Fecha Nacimiento" style="font-size: 1.3rem;"  name="fechnac">
                            <label for="floatingInput">Fecha Nacimiento</label>
                        </div>

                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="text" class="form-control" id="id_rut" placeholder="Rut" style="font-size: 1.3rem;"  name="rut">
                            <label for="floatingPassword">Rut</label>
                        </div>
                        
                        <div class="d-flex justify-content-between">
                            <button type="submit" class="btn btn-outline-success" href="#" role="button" style="background-color: #67cb57; border-radius: 5rem; padding:.9rem 3.5rem;">Registrarse</button>
                        </div>

                    </div>
                </form>   
            </div> 
        </div>
    </div> 
</section>
{% endblock %}
{% block js %}
<script src="{% static 'core/jquery.rut.min.js' %}"></script>
{% endblock %}

FlowerScrets/core/templates/core/arbustos.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<!------------------------------SLIDER---------------------------------->
    <section class="home-slider" id="home-slider">
        <div class="contenido-slider">
            <h3>Arbustos y Arboles</h3>
            <p>Hermosos Arbustos para el jardin</p>
            <a class="btn btn-outline-success" href="#producto" role="button" style="background-color: #67cb57; border-radius: 5rem; padding:.9rem 3.5rem;">Comprar Ahora</a>
        </div>

        <div class="controles">
            <span class="vid-btn active" data-src="images/slider_arbusto.png"></span>
            <span class="vid-btn" data-src="images/slider_ar4.jpg"></span>
            <span class="vid-btn" data-src="images/slider_ar6.jpg"></span>
        </div>

        <div class="image-container">
            <img src="{% static 'core/images/slider_arbusto.png' %}" id="imagen-slider" alt="">
        </div>

    </section>

{% endblock %}

{% block content_productos %}
<!--BOTON DE COMPARTIR-->
<div class="modal fade" id="shapeModal" aria-hidden="true" tabindex="-1" aria-labelledby="modalTitle">
    <div class="modal-dialog modal-dialog-centered" style="max-width: 500px; height: 500px;">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title" style="font-size: 3rem;">Compartir</h3>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="popup">
                <div class="content">
                    <ul class="icons">
                        <a href="https://www.facebook.com/" target="_BLANK"><i class="fab fa-facebook"><p></p></i></a>
                        <a href="https://www.twitter.com/" target="_BLANK"><i class="fab fa-twitter"></i></a>
                        <a href="https://www.instagram.com/" target="_BLANK"><i class="fab fa-instagram"></i></a>
                        <a href="https://www.whatsapp.com/" target="_BLANK"><i class="fab fa-whatsapp"></i></a>
                    </ul>
                </div>
            </div>
        </div>
      </div>
    </div>
</div>

<!---------------------------------------------PRODUCTO 1------------------------------------------------->
<section class="productos" id="producto">

    <div class="box-container">

        <div class="box">
            <span class="descuento">-5%</span>
            <div class="image">
                <img src="https://media.easy.cl/is/image/EasySA/1317505-01?height=320&width=400&format=jpg&ver=1627511347346" style="width: 350px; height: 350px;" alt="">
                <div class="iconos">
                    <a class="fa fa-cart-plus"  data-bs-target="#miModal" data-bs-toggle="modal"></a>
                    <a class="fas fa fa-share" data-bs-target="#shapeModal" data-bs-toggle="modal"></a>
                </div>
            </div>

            <div class="contenido">
                <h3>Naranjo</h3>
                <div class="precio">$57.000 <span>60.000</span></div>
            </div>
        </div>
<!------------------------------------MODAL------------------------------------------------------> 
<div class="modal fade" id="miModal" aria-hidden="true" tabindex="-1" aria-labelledby="modalTitle">
    <div class="modal-dialog modal-dialog-centered" style="max-width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="modalTitle" style="color: #333; font-size: 2.5rem;">Naranjo</h3>
                <h3 class="modal-dialog">$57.000 </h3>
                                    <!--BOTON DE CIERRE-->
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="width: 3rem;"></button>
            </div>
            <div class="modal-body">
                <div class="modal-fullscreen"><img src="https://media.easy.cl/is/image/EasySA/1317505-01?height=320&width=400&format=jpg&ver=1627511347346" style="width: 350px; height: 350px;"></div>

                <div class="form-group">
                    <label for="Cantidad">Cantidad</label>
                    <select name="identificador" id="identificador" class="form-select" style="width:30%; height:35px; font-size: 1.3rem;">
                        <option value="1" style="font-size: 1.3rem;">1</option>
                        <option value="2" style="font-size: 1.3rem;">2</option>
                        <option value="3" style="font-size: 1.3rem;">3</option>
                        <option value="4" style="font-size: 1.3rem;">4</option>
                    </select>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Agregar Al Carro</button>
            </div>
        </div>
    </div>
</div>
        
<!---------------------------------------------PRODUCTO 2------------------------------------------------->
        <div class="box">
            <span class="descuento">-10%</span>
            <div class="image">
                <img src="https://falabella.scene7.com/is/image/Falabella/881425062_1?wid=800&hei=800&qlt=70" style="width: 350px; height: 350px;" alt="">
                <div class="iconos">
                    <a class="fa fa-cart-plus"  data-bs-target="#miModal2" data-bs-toggle="modal"></a>
                    <a class="fas fa fa-share" data-bs-target="#shapeModal" data-bs-toggle="modal"></a>
                </div>
            </div>

            <div class="contenido">
                <h3>Ficus</h3>
                <div class="precio">$58.500 <span>$65.000</span></div>
            </div>
        </div>
<!-----------------------------------------------PRODUCTO MODAL 2----------------------------------------------------------->
<div class="modal fade" id="miModal2" aria-hidden="true" tabindex="-1" aria-labelledby="modalTitle">
    <div class="modal-dialog modal-dialog-centered" style="max-width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="modalTitle" style="color: #333; font-size: 2.5rem;">Ficus</h3>
                <h3 class="modal-dialog">$58.500</h3>
                                    <!--BOTON DE CIERRE-->
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="width: 3rem;"></button>
            </div>
            <div class="modal-body">
                <div class="modal-fullscreen"><img src="https://falabella.scene7.com/is/image/Falabella/881425062_1?wid=800&hei=800&qlt=70" style="height: 300px;"></div>

                <div class="form-group">
                    <label for="Cantidad">Cantidad</label>
                    <select name="identificador" id="identificador" class="form-select" style="width:30%; height:35px; font-size: 1.3rem;">
                        <option value="1" style="font-size: 1.3rem;">1</option>
                        <option value="2" style="font-size: 1.3rem;">2</option>
                        <option value="3" style="font-size: 1.3rem;">3</option>
                        <option value="4" style="font-size: 1.3rem;">4</option>
                    </select>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Agregar Al Carro</button>
            </div>
        </div>
    </div>
</div>

<!---------------------------------------------PRODUCTO 3------------------------------------------------->
        <div class="box">
            <span class="descuento">-5%</span>
            <div class="image">
                <img src="https://www.paris.cl/dw/image/v2/BCHW_PRD/on/demandware.static/-/Sites-paris-marketplace/default/dwc679f8bf/images/imagenes-productos/800/MKC2/MKC2B4VVLB-001.jpg?sw=513&sh=654&sm=fit" style="width: 350px; height: 350px;" alt="">
                <div class="iconos">
                    <a class="fa fa-cart-plus"  data-bs-target="#miModal3" data-bs-toggle="modal"></a>
                    <a class="fas fa fa-share" data-bs-target="#shapeModal" data-bs-toggle="modal"></a>
                </div>
            </div>

            <div class="contenido">
                <h3>Olivo</h3>
                <div class="precio">$42.750 <span>$45.000</span></div>
            </div>
        </div>

<!-----------------------------------------------PRODUCTO MODAL 3----------------------------------------------------------->
<div class="modal fade" id="miModal3" aria-hidden="true" tabindex="-1" aria-labelledby="modalTitle">
    <div class="modal-dialog modal-dialog-centered" style="max-width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="modalTitle" style="color: #333; font-size: 2.5rem;">Olivo</h3>
                <h3 class="modal-dialog">$42.750 </h3>
                                    <!--BOTON DE CIERRE-->
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="width: 3rem;"></button>
            </div>
            <div class="modal-body">
                <div class="modal-fullscreen"><img src="https://www.paris.cl/dw/image/v2/BCHW_PRD/on/demandware.static/-/Sites-paris-marketplace/default/dwc679f8bf/images/imagenes-productos/800/MKC2/MKC2B4VVLB-001.jpg?sw=513&sh=654&sm=fit" style="height: 300px;"></div>

                <div class="form-group">
                    <label for="Cantidad">Cantidad</label>
                    <select name="identificador" id="identificador" class="form-select" style="width:30%; height:35px; font-size: 1.3rem;">
                        <option value="1" style="font-size: 1.3rem;">1</option>
                        <option value="2" style="font-size: 1.3rem;">2</option>
                        <option value="3" style="font-size: 1.3rem;">3</option>
                        <option value="4" style="font-size: 1.3rem;">4</option>
                    </select>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Agregar Al Carro</button>
            </div>
        </div>
    </div>
</div>

    </div>
</section>



{% endblock %}

FlowerScrets/core/templates/core/flores.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<!------------------------SLIDER---------------------------------------------->
<section class="home-slider" id="home-slider">
    <div class="contenido-slider">
        <h3>Flores</h3>
        <p>Las mejores flores para tu jardin y casa</p>

        <a class="btn btn-outline-success" href="#producto" role="button" style="background-color: #67cb57; border-radius: 5rem; padding:.9rem 3.5rem;">Comprar Ahora</a>
    </div>

    <div class="controles">
        <span class="vid-btn active" data-src="{% static 'images/home-bg.jpg' %}"></span>
        <span class="vid-btn" data-src="{% static 'core/images/home-bg.jpg' %}"></span>
        <span class="vid-btn" data-src="{% static 'core/images/home-bg.jpg' %}"></span>
    </div>

    <div class="image-container">
        <img src="{% static 'core/images/home-bg.jpg' %}" id="imagen-slider" alt="">
    </div>

</section>

{% endblock %}


{% block content_productos %}
<!--BOTON DE COMPARTIR-->
<div class="modal fade" id="shapeModal" aria-hidden="true" tabindex="-1" aria-labelledby="modalTitle">
    <div class="modal-dialog modal-dialog-centered" style="max-width: 500px; height: 500px;">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="modal-title" style="font-size: 3rem;">Compartir</h3>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="popup">
                <div class="content">
                    <ul class="icons">
                        <a href="https://www.facebook.com/" target="_BLANK"><i class="fab fa-facebook"><p></p></i></a>
                        <a href="https://www.twitter.com/" target="_BLANK"><i class="fab fa-twitter"></i></a>
                        <a href="https://www.instagram.com/" target="_BLANK"><i class="fab fa-instagram"></i></a>
                        <a href="https://www.whatsapp.com/" target="_BLANK"><i class="fab fa-whatsapp"></i></a>
                    </ul>
                </div>
            </div>
        </div>
      </div>
    </div>
</div>
<!---------------------------------------------PRODUCTOS------------------------------------------------->
<section class="productos" id="producto">

    <div class="box-container">
        {%for p in flores %}
            <div class="box">
                <span class="descuento">-5%</span>
                <div class="image">
                    <img src="{{p.imagen.url}}" alt=""  style="width: 300px; height: 300px;">
                    <div class="iconos">
                        <a class="fa fa-cart-plus"  data-bs-target="#miModal{{p.idProducto}}" data-bs-toggle="modal"></a>
                        <a class="fas fa fa-share" data-bs-target="#shapeModal" data-bs-toggle="modal"></a>
                    </div>
                </div>

                <div class="contenido">
                    <h3>{{p.nombre}}</h3>
                    <div class="precio">${{p.precio}} <span>$21.000</span></div>
                </div>
            </div>
        {% endfor %}
    </div>
</section>


<!------------------------------------MODAL------------------------------------------------------> 
{%for p in flores %}
<div class="modal fade" id="miModal{{p.idProducto}}" aria-hidden="true" tabindex="-1" aria-labelledby="modalTitle">
    <div class="modal-dialog modal-dialog-centered" style="max-width: 800px;">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="modalTitle" style="color: #333; font-size: 2.5rem;">{{p.nombre}}</h3>
                <h3 class="modal-dialog">${{p.precio}}</h3>
                                    <!--BOTON DE CIERRE-->
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" style="width: 3rem;"></button>
            </div>
            <div class="modal-body">
                <div class="modal-fullscreen"><img src="{{p.imagen.url}}" style="height: 300px;"></div>

                <div class="form-group">
                    <label for="Cantidad">Cantidad</label>
                    <select name="identificador" id="identificador" class="form-select" style="width:30%; height:35px; font-size: 1.3rem;">
                        <option value="1" style="font-size: 1.3rem;">1</option>
                        <option value="2" style="font-size: 1.3rem;">2</option>
                        <option value="3" style="font-size: 1.3rem;">3</option>
                        <option value="4" style="font-size: 1.3rem;">4</option>
                    </select>
                </div>

            </div>
            <div class="modal-footer">
                <a href="{% url 'Add' p.idProducto %}" class="btn btn-primary">Agregar Al Carro</a>
            </div>
        </div>
    </div>
</div>
    {% endfor %}
{% endblock %}

FlowerScrets/core/templates/core/logeo.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}
<section class="formulario">
    <div class="row">

        <div class="col-lg-5 p-3" style="background: rgb(253, 254, 254,.3);">
            <img src="{% static 'core/images/img_reg.png' %}" alt="" style="height: 300px;" height="300px">
        </div>

        <div class="col-lg-7 p-5" style="background: rgb(253, 254, 254,.3);">
            <div class="signup-form">
                <form method="post" class="mt-5 border p-5 bg-light shadow" id="formulariologeo">
                    {% csrf_token %}
                    <h3>INICIO DE SESION</h3>
                    <div class="row">
                        <div class="alert alert-danger" role="alert" id="alerta">
                        </div>

                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="text" class="form-control" id="id_email"  name="correo_login" placeholder="Nombre" style="font-size: 1.3rem;"/>
                            <label for="floatingInput">correo</label>
                        </div>
                        <div class="form-floating mb-3 col-6 p-2">
                            <input type="password" class="form-control"  id="id_pass" placeholder="contraseña" style="font-size: 1.3rem;"  name="password_login"/>
                            <label for="floatingInput">contraseña</label>
                        </div>
                        <div class="d-flex justify-content-between">
                            <button type="submit" class="btn btn-outline-success" href="#" role="button" style="background-color: #67cb57; border-radius: 5rem; padding:.9rem 3.5rem;">Logear</button>
                        </div>

                    </div>
                </form>
            </div> 
        </div>
    </div> 
</section>
{% endblock %}
{% block js %}
<script src="{% static 'core/jquery.rut.min.js' %}"></script>
{% endblock %}

FlowerScrets/core/templates/core/pago.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>funciona</h1>
</body>
</html>